spring.application.name=event-ai

server.port=8080

gemini.api-key=AIzaSyAtr-SpOzWM9cpau59PV_L7-bkN0z9e7Iw
gemini.model=gemini-2.5-flash

resilience4j.circuitbreaker.instances.geminiAssistant.slidingWindowSize=20
resilience4j.circuitbreaker.instances.geminiAssistant.minimumNumberOfCalls=10
resilience4j.timelimiter.instances.geminiAssistant.timeoutDuration=60s
